[package]
name = "glowpub"
version = "0.3.0"
authors = ["QuartzLibrary"]
license = "MIT OR Apache-2.0"
description = "A glowfic to epub converter."
repository = "https://github.com/QuartzLibrary/glowpub"
readme = "README.md"
edition = "2024"

[features]
default = ["binary"]
binary = ["epub", "dep:clap", "dep:simple_logger", "dep:slug"]
epub = ["gen", "api", "dep:epub-builder", "dep:uuid"]
api = ["dep:serde_json", "dep:tokio", "dep:glob", "dep:rpassword"]
gen = ["dep:fontdb", "dep:resvg", "dep:textwrap", "dep:tiny-skia", "dep:usvg", "dep:ammonia", "dep:cssparser", "dep:html-escape", "dep:html5ever", "dep:lightningcss", "dep:lol_html", "dep:markup5ever", "dep:markup5ever_rcdom", "dep:xml5ever"]

[dependencies]
log = "0.4"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
mime = "0.3"
sha2 = "0.10"
reqwest = { version = "0.12", features = ["json"] }
image = { version = "0.25", default-features = false, features = ["bmp", "gif", "jpeg", "png", "webp"] }

serde_json = { version ="1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
glob = { version = "0.3", optional = true }
rpassword = { version = "7.3.1", optional = true }

fontdb = { version = "0.16", optional = true }
resvg = { version = "0.41", optional = true }
textwrap = { version = "0.16", optional = true }
tiny-skia = { version = "0.11", optional = true }
usvg = { version = "0.41", optional = true }

ammonia = { version = "4", optional = true }
cssparser = { version = "0.33", optional = true }
html-escape = { version = "0.2", optional = true }
html5ever = { version = "0.27", optional = true }
lightningcss = { version = "1.0.0-alpha.55", optional = true }
lol_html = { version = "1", optional = true }
markup5ever = { version = "0.12", optional = true }
markup5ever_rcdom = { version = "0.3", optional = true }
xml5ever = { version = "0.18", optional = true }

epub-builder = { version = "0.7", default-features = false, features = ["libzip"], optional = true }
uuid = { version = "1", features = ["v4"], optional = true }

clap = { version = "4", features = ["derive"], optional = true }
simple_logger = { version = "4", optional = true }
slug = { version = "0.1", optional = true }
