[package]
name = "glowpub"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
mime = "0.3"
tokio = { version = "1", features = ["full"] }
glob = "0.3"
regex = "1"
chrono = { version = "0.4", features=["serde"] }
uuid = { version = "1", features = ["v4"] }
rand = "0.8"

textwrap = "0.16"
resvg = "0.28"
usvg = "0.28"
tiny-skia = "0.8"
fontdb = "0.10"
usvg-text-layout = "0.28.0"

ammonia = "3"
lol_html = "0.3.2"
html5ever = "0.26.0"
xml5ever = "0.17.0"
markup5ever_rcdom = "0.2.0"
markup5ever = "0.11.0"

[dependencies.epub-builder]
git = "https://github.com/QuartzLibrary/epub-builder"
branch = "reproducible"
default-features = false
features = ["libzip"]

[dev-dependencies]
clap = { version = "3.1", features = ["derive"] }
